name: Build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node 17
        uses: actions/setup-node@v3
        with:
          node-version: '17.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@coderatparadise'
          cache: 'yarn'
      - run: yarn
      - run: yarn lint
      - run: yarn build